services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: travel_orders_frontend
    restart: always
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules

